version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    env_file:
      - .env
    ports:
      - "8200:8200"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-balout}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3326:3306"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
